name: Auto Merge PR (discard changes)

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty merge commit
        run: |
          PR_BRANCH=${{ github.event.pull_request.head.ref }}
          git fetch origin $PR_BRANCH
          # Merge PR branch but ignore all changes
          git merge --allow-unrelated-histories --no-commit --no-ff FETCH_HEAD
          git reset --hard HEAD  # discard all changes
          git commit --allow-empty -m "Merge PR #${{ github.event.pull_request.number }} (discard changes)"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}

      - name: Close PR on GitHub
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --merge \
            --delete-branch
