name: Auto Merge PR

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}