name: Auto Merge PR

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Merge base into PR branch
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git merge origin/${{ github.event.pull_request.base.ref }} --no-edit || echo "Merge conflicts detected, skipping merge"

      - name: Merge PR automatically
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
        run: |
          echo "Merging PR #${{ github.event.pull_request.number }} automatically"
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --merge \
            --delete-branch
