name: Fake Merge PR (no file changes)

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  fake-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty merge commit
        run: |
          git commit --allow-empty -m "Fake merge PR #${{ github.event.pull_request.number }} (discard changes)"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}

      - name: Close PR
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --delete-branch
