name: Fake Merge PR (empty, no file changes)

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch PR branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Create empty merge commit
        run: |
          # Merge PR branch without applying changes
          git merge --allow-unrelated-histories --no-commit FETCH_HEAD || true
          git reset --hard HEAD
          git commit --allow-empty -m "Merge PR #${{ github.event.pull_request.number }} (discard changes)"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}

      - name: Mark PR as merged
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --merge \
            --delete-branch
